package hr.fer.zemris.java.hw06.shell.commands;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import hr.fer.zemris.java.hw06.shell.ShellTokenizer;

/**
 * A utility class which provides two <code>public static</code>
 * method.
 * <p>
 * One is used for splitting the command arguments given the arguments string.
 * <p>
 * The second is used to shed the path string of enclosing quotes generated by
 * {@link ShellTokenizer}.
 * 
 * @author Ivan Skorupan
 */
public class CommandUtil {
	
	/**
	 * Key used for stack management in shared command data map.
	 */
	protected static final String STACK_KEY = "cdstack";
	
	/**
	 * Splits the arguments string into discrete argument strings and returns
	 * a string array of those arguments.
	 * <p>
	 * This method uses {@link ShellTokenizer} in order to split
	 * the argument string.
	 * 
	 * @param arguments - string containing all arguments for a command
	 * @return string array containing split arguments
	 * @throws NullPointerException if <code>arguments</code> is <code>null</code>
	 */
	public static String[] getSplitCommandInput(String arguments) {
		Objects.requireNonNull(arguments);
		ShellTokenizer tokenizer = new ShellTokenizer(arguments);
		List<String> args = new ArrayList<>();
		tokenizer.nextToken();
		
		while(tokenizer.getToken() != null) {
			args.add(tokenizer.getToken());
			tokenizer.nextToken();
		}
		
		String[] array = new String[args.size()];
		for(int i = 0; i < args.size(); i++) {
			array[i] = args.get(i);
		}
		
		return array;
	}
	
	/**
	 * Takes a string and sheds off unnecessary double quotes surrounding it.
	 * <p>
	 * If the string is not surrounded by double quotes, this method trivially
	 * returns the unmodified argument <code>text</code>.
	 * 
	 * @param text - a string to shed
	 * @return given string whose enclosing quotes have been deleted
	 * @throws NullPointerException if <code>text</code> is <code>null</code>
	 */
	public static String shedString(String text) {
		Objects.requireNonNull(text);
		
		if(text.startsWith("\"") && text.endsWith("\"")) {
			return text.substring(1, text.length() - 1);
		} else {
			return text;
		}
	}
	
}
