package hr.fer.zemris.java.custom.scripting.lexer;

import java.util.Objects;

/**
 * A model of a single token generated by {@link SmartScriptLexer} object.
 * 
 * @author Ivan Skorupan
 */
public class SmartScriptToken {
	
	/**
	 * This token's type.
	 */
	private SmartScriptTokenType type;
	
	/**
	 * This token's value.
	 */
	private Object value;
	
	/**
	 * Constructs a new {@link SmartScriptToken} object.
	 * 
	 * @param type - type of this token
	 * @param value - value of this token
	 */
	public SmartScriptToken(SmartScriptTokenType type, Object value) {
		this.type = Objects.requireNonNull(type);
		this.value = value;
	}
	
	/**
	 * Getter for this token's <code>value</code>.
	 * 
	 * @return this token's <code>value</code>
	 */
	public Object getValue() {
		return this.value;
	}
	
	/**
	 * Getter for this token's <code>type</code>.
	 * 
	 * @return this token's <code>type</code>
	 */
	public SmartScriptTokenType getType() {
		return this.type;
	}
	
}
