package hr.fer.zemris.java.hw05.db.lexer;

import java.util.Objects;

/**
 * A model of a single token generated by {@link QueryLexer} object.
 * 
 * @author Ivan Skorupan
 */
public class QueryToken {
	
	/**
	 * This token's type.
	 */
	private QueryTokenType type;
	
	/**
	 * This token's value.
	 */
	private Object value;
	
	/**
	 * Constructs a new {@link SmartScriptToken} object.
	 * 
	 * @param type - type of this token
	 * @param value - value of this token
	 */
	public QueryToken(QueryTokenType type, Object value) {
		this.type = Objects.requireNonNull(type);
		this.value = value;
	}
	
	/**
	 * Getter for this token's <code>value</code>.
	 * 
	 * @return this token's <code>value</code>
	 */
	public Object getValue() {
		return this.value;
	}
	
	/**
	 * Getter for this token's <code>type</code>.
	 * 
	 * @return this token's <code>type</code>
	 */
	public QueryTokenType getType() {
		return this.type;
	}
	
}
