package hr.fer.zemris.java.hw06.shell.commands.namelexer;

import java.util.Objects;

/**
 * Models a token that can be generated by {@link NameBuilderLexer}.
 * 
 * @author Ivan Skorupan
 */
public class NameBuilderToken {
	
	/**
	 * Value of this token.
	 */
	private String value;
	
	/**
	 * This token's type.
	 */
	private NameBuilderTokenType type;
	
	/**
	 * Constructs a new {@link NameBuilderToken} object.
	 * 
	 * @param value
	 * @throws NullPointerException if <code>type</code> is <code>null</code>
	 */
	public NameBuilderToken(NameBuilderTokenType type, String value) {
		this.type = Objects.requireNonNull(type);
		this.value = value;
	}
	
	/**
	 * Returns this token's type.
	 * 
	 * @return type of this token
	 */
	public NameBuilderTokenType getType() {
		return type;
	}
	
	/**
	 * Returns this token's value.
	 * 
	 * @return value of this token
	 */
	public String getValue() {
		return value;
	}
}
